// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package sdj.project.eventcalendar.protobuf;

public final class EventOuterClass {
  private EventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdj_project_eventcalendar_protobuf_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdj_project_eventcalendar_protobuf_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022\"sdj.project.eventcalendar" +
      ".protobuf\032\nUser.proto\"n\n\005Event\022\020\n\010event_" +
      "id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010bodytext\030\003 \001(\t" +
      "\022\021\n\tstartTime\030\004 \001(\t\022\017\n\007endTime\030\005 \001(\t\022\017\n\007" +
      "address\030\006 \001(\t2\265\004\n\020GRPCEventService\022\200\001\n%R" +
      "PCserverSideStreamingGetListOfEvents\022(.s" +
      "dj.project.eventcalendar.protobuf.User\032)" +
      ".sdj.project.eventcalendar.protobuf.Even" +
      "t\"\0000\001\022h\n\020RPCfindEventById\022).sdj.project." +
      "eventcalendar.protobuf.Event\032).sdj.proje" +
      "ct.eventcalendar.protobuf.Event\022d\n\014RPCsa" +
      "veEvent\022).sdj.project.eventcalendar.prot" +
      "obuf.Event\032).sdj.project.eventcalendar.p" +
      "rotobuf.Event\022f\n\016RPCupdateEvent\022).sdj.pr" +
      "oject.eventcalendar.protobuf.Event\032).sdj" +
      ".project.eventcalendar.protobuf.Event\022f\n" +
      "\016RPCdeleteEvent\022).sdj.project.eventcalen" +
      "dar.protobuf.Event\032).sdj.project.eventca" +
      "lendar.protobuf.EventB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sdj.project.eventcalendar.protobuf.UserOuterClass.getDescriptor(),
        });
    internal_static_sdj_project_eventcalendar_protobuf_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sdj_project_eventcalendar_protobuf_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdj_project_eventcalendar_protobuf_Event_descriptor,
        new java.lang.String[] { "EventId", "Name", "Bodytext", "StartTime", "EndTime", "Address", });
    sdj.project.eventcalendar.protobuf.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
