// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package sdj.project.eventcalendar.protobuf;

public final class EventOuterClass {
  private EventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdj_project_eventcalendar_protobuf_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdj_project_eventcalendar_protobuf_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022\"sdj.project.eventcalendar" +
      ".protobuf\032\nUser.proto\"\251\001\n\005Event\022\020\n\010event" +
      "_id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010bodytext\030\003 \001(" +
      "\t\022\021\n\tstartTime\030\004 \001(\t\022\017\n\007endTime\030\005 \001(\t\022\017\n" +
      "\007address\030\006 \001(\t\0229\n\007creator\030\007 \001(\0132(.sdj.pr" +
      "oject.eventcalendar.protobuf.User2\361\007\n\020GR" +
      "PCEventService\022s\n\030RPCGetListOfUsersinEve" +
      "nt\022).sdj.project.eventcalendar.protobuf." +
      "Event\032(.sdj.project.eventcalendar.protob" +
      "uf.User\"\0000\001\022t\n\031RPCGetListofCreatedEvents" +
      "\022(.sdj.project.eventcalendar.protobuf.Us" +
      "er\032).sdj.project.eventcalendar.protobuf." +
      "Event\"\0000\001\022s\n\030RPCGetListOfJoinedEvents\022(." +
      "sdj.project.eventcalendar.protobuf.User\032" +
      ").sdj.project.eventcalendar.protobuf.Eve" +
      "nt\"\0000\001\022m\n\022RPCGetListOfEvents\022(.sdj.proje" +
      "ct.eventcalendar.protobuf.User\032).sdj.pro" +
      "ject.eventcalendar.protobuf.Event\"\0000\001\022n\n" +
      "\024RPCGetListOfAllUsers\022(.sdj.project.even" +
      "tcalendar.protobuf.User\032(.sdj.project.ev" +
      "entcalendar.protobuf.User\"\0000\001\022h\n\020RPCfind" +
      "EventById\022).sdj.project.eventcalendar.pr" +
      "otobuf.Event\032).sdj.project.eventcalendar" +
      ".protobuf.Event\022d\n\014RPCsaveEvent\022).sdj.pr" +
      "oject.eventcalendar.protobuf.Event\032).sdj" +
      ".project.eventcalendar.protobuf.Event\022f\n" +
      "\016RPCupdateEvent\022).sdj.project.eventcalen" +
      "dar.protobuf.Event\032).sdj.project.eventca" +
      "lendar.protobuf.Event\022f\n\016RPCdeleteEvent\022" +
      ").sdj.project.eventcalendar.protobuf.Eve" +
      "nt\032).sdj.project.eventcalendar.protobuf." +
      "EventB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sdj.project.eventcalendar.protobuf.UserOuterClass.getDescriptor(),
        });
    internal_static_sdj_project_eventcalendar_protobuf_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sdj_project_eventcalendar_protobuf_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdj_project_eventcalendar_protobuf_Event_descriptor,
        new java.lang.String[] { "EventId", "Name", "Bodytext", "StartTime", "EndTime", "Address", "Creator", });
    sdj.project.eventcalendar.protobuf.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
